application: recreoplus
version: 1
runtime: python
api_version: 1

handlers:

- url: /image
  static_dir: template/image

- url: /css
  static_dir: template/css

- url: /js
  static_dir: template/javascript

- url: /.*
  script: picsdiary.py
